<template>
    <div class="malebreed-view">
        <!-- Start All Title Box -->
        <div class="all-title-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>Male Breed</h2>
                    </div>
                </div>
            </div>
        </div>
        <!-- End All Title Box -->

        <div class="categories-shop">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="title-all text-center">
                            <h1>Male Breed Puppies</h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="shop-cat-box">
                            <img class="img-fluid" src="images/puppies.jpg" alt="" />
                            <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="shop-cat-box">
                            <img class="img-fluid" src="images/puppies.jpg" alt="" />
                            <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="shop-cat-box">
                            <img class="img-fluid" src="images/puppies.jpg" alt="" />
                            <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                      <div class="shop-cat-box">
                          <img class="img-fluid" src="images/puppies.jpg" alt="" />
                          <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                      </div>
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                      <div class="shop-cat-box">
                          <img class="img-fluid" src="images/puppies.jpg" alt="" />
                          <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                      </div>
                  </div>
                  <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                      <div class="shop-cat-box">
                          <img class="img-fluid" src="images/puppies.jpg" alt="" />
                          <a class="btn hvr-hover" href="#">Lorem ipsum dolor</a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
    </div>
</template>